In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [2]:
from keras.layers import Dense,Activation
from keras.models import Sequential
from keras.utils import np_utils

Using TensorFlow backend.


In [3]:
df = pd.read_csv('./titanic.csv')
test_file = pd.read_csv('./test.csv')

In [4]:
print df.shape
print df.columns

(891, 12)
Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')


In [5]:
df = df.drop(['Name'],axis=1)
test_file = test_file.drop(['Name'],axis=1)

In [6]:
print df.columns
print test_file.columns

Index([u'PassengerId', u'Survived', u'Pclass', u'Sex', u'Age', u'SibSp',
       u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')
Index([u'PassengerId', u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch',
       u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')


In [7]:
print df['Sex'].isnull().values.any()
# np_utils.to_categorical?

False


In [8]:
# df = df.values
# test_file = test_file.values

In [9]:
# Sex = df['Sex']

In [10]:
# print type(df['Sex'])
# print len(Sex)
# print type(Sex)
# Sex = np.array(Sex)

In [11]:
# print type(Sex)

In [12]:
# df['Sex'] = np_utils.to_categorical(Sex)

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
df = df.apply(le.fit_transform)

In [16]:
ids = test_file['PassengerId']

In [17]:
# print ids

In [18]:
# print df

In [19]:
le2 = LabelEncoder()
test_file = test_file.apply(le2.fit_transform)

In [20]:
# print test_file

In [21]:
df = df.drop(['PassengerId'],axis=1)
test_file = test_file.drop(['PassengerId'],axis=1)

In [22]:
print df.columns
print test_file.columns

Index([u'Survived', u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Ticket',
       u'Fare', u'Cabin', u'Embarked'],
      dtype='object')
Index([u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Ticket', u'Fare',
       u'Cabin', u'Embarked'],
      dtype='object')


In [23]:
df['Sex'] = np_utils.to_categorical(df['Sex'])
test_file['Sex'] = np_utils.to_categorical(test_file['Sex'])

In [24]:
df = df.values
test_file = test_file.values

In [25]:
print df[:5]

[[   0.    2.    0.   28.    1.    0.  523.   18.    0.    4.]
 [   1.    0.    1.   51.    1.    0.  596.  207.  768.    2.]
 [   1.    2.    1.   34.    0.    0.  669.   41.  509.    4.]
 [   1.    0.    1.   47.    1.    0.   49.  189.  742.    4.]
 [   0.    2.    0.   47.    0.    0.  472.   43.  510.    4.]]


In [26]:
print type(df)
print type(test_file)
print df[:10]

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
[[   0.    2.    0.   28.    1.    0.  523.   18.    0.    4.]
 [   1.    0.    1.   51.    1.    0.  596.  207.  768.    2.]
 [   1.    2.    1.   34.    0.    0.  669.   41.  509.    4.]
 [   1.    0.    1.   47.    1.    0.   49.  189.  742.    4.]
 [   0.    2.    0.   47.    0.    0.  472.   43.  510.    4.]
 [   0.    2.    0.  110.    0.    0.  275.   51.  511.    3.]
 [   0.    0.    0.   69.    0.    0.   85.  186.  816.    4.]
 [   0.    2.    0.    6.    3.    1.  395.  124.  512.    4.]
 [   1.    2.    1.   35.    0.    2.  344.   74.  513.    4.]
 [   1.    1.    1.   18.    1.    0.  132.  154.  514.    2.]]


In [27]:
print df[:10,0]

[ 0.  1.  1.  1.  0.  0.  0.  0.  1.  1.]


In [28]:
split = int(0.75*df.shape[0])
print split

train_x = df[:split,1:]
train_y = df[:split,0]
test_x = df[split:,1:]
test_y = df[split:,0]
print train_x.shape,train_y.shape
print test_x.shape,test_y.shape

668
(668, 9) (668,)
(223, 9) (223,)


In [29]:
from keras.utils import np_utils 

In [30]:
train_yy = np_utils.to_categorical(train_y)
test_yy = np_utils.to_categorical(test_y)
print train_yy.shape
print test_yy.shape

(668, 2)
(223, 2)


In [31]:
model = Sequential()
model.add(Dense(5, input_shape=(9,)))
model.add(Activation('relu'))

# model.add(Dense(4))
# model.add(Activation('relu'))

model.add(Dense(2))
model.add(Activation('softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 5)                 50        
_________________________________________________________________
activation_1 (Activation)    (None, 5)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 12        
_________________________________________________________________
activation_2 (Activation)    (None, 2)                 0         
Total params: 62
Trainable params: 62
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [33]:
model.fit(train_x,train_yy,batch_size=8,nb_epoch=15,verbose=2,validation_data=(test_x,test_yy))

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 668 samples, validate on 223 samples
Epoch 1/15
 - 1s - loss: 9.7610 - acc: 0.3892 - val_loss: 9.6174 - val_acc: 0.3677
Epoch 2/15
 - 0s - loss: 4.7302 - acc: 0.5404 - val_loss: 2.4840 - val_acc: 0.6726
Epoch 3/15
 - 0s - loss: 2.7530 - acc: 0.6332 - val_loss: 1.7814 - val_acc: 0.6951
Epoch 4/15
 - 0s - loss: 2.1226 - acc: 0.6467 - val_loss: 1.2746 - val_acc: 0.7220
Epoch 5/15
 - 0s - loss: 1.8050 - acc: 0.6632 - val_loss: 1.1602 - val_acc: 0.7309
Epoch 6/15
 - 0s - loss: 1.6417 - acc: 0.6632 - val_loss: 1.0932 - val_acc: 0.7220
Epoch 7/15
 - 0s - loss: 1.4829 - acc: 0.6662 - val_loss: 1.1084 - val_acc: 0.7265
Epoch 8/15
 - 0s - loss: 1.4450 - acc: 0.6632 - val_loss: 1.0230 - val_acc: 0.7265
Epoch 9/15
 - 0s - loss: 1.4214 - acc: 0.6587 - val_loss: 1.0276 - val_acc: 0.7265
Epoch 10/15
 - 0s - loss: 1.4150 - acc: 0.6632 - val_loss: 1.0287 - val_acc: 0.7265
Epoch 11/15
 - 0s - loss: 1.4136 - acc: 0.6632 - val_loss: 1.0228 - val_acc: 0.7265
Epoch 12/15
 - 0s - loss: 1.4081 - acc:

In [34]:
#now we will try droping out some connections(which should not be a good idea as data is small)

In [35]:
from keras.layers import Dropout

In [36]:
model2 = Sequential()
model2.add(Dense(3,input_shape=(9,)))
model2.add(Activation('relu'))
model2.add(Dropout(0.2))

model2.add(Dense(2))
model2.add(Activation('sigmoid'))
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 3)                 30        
_________________________________________________________________
activation_3 (Activation)    (None, 3)                 0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 3)                 0         
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 8         
_________________________________________________________________
activation_4 (Activation)    (None, 2)                 0         
Total params: 38
Trainable params: 38
Non-trainable params: 0
_________________________________________________________________


In [37]:
model2.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [38]:
model2.fit(train_x,train_yy,epochs=15,batch_size=8,verbose=2,validation_data=(test_x,test_yy))

Train on 668 samples, validate on 223 samples
Epoch 1/15
 - 1s - loss: 7.8472 - acc: 0.3997 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 2/15
 - 0s - loss: 8.3873 - acc: 0.3952 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 3/15
 - 0s - loss: 8.0811 - acc: 0.4057 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 4/15
 - 0s - loss: 8.1514 - acc: 0.4012 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 5/15
 - 0s - loss: 7.8937 - acc: 0.3922 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 6/15
 - 0s - loss: 7.8733 - acc: 0.3907 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 7/15
 - 0s - loss: 7.6910 - acc: 0.3997 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 8/15
 - 0s - loss: 7.8645 - acc: 0.3937 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 9/15
 - 0s - loss: 8.0008 - acc: 0.3952 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 10/15
 - 0s - loss: 7.7204 - acc: 0.3922 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 11/15
 - 0s - loss: 8.0142 - acc: 0.3937 - val_loss: 10.1913 - val_acc: 0.3677
Epoch 12/15
 - 0s - loss: 7.

In [ ]:
# thus we got 72% accuracy with our previous model on validation data