In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [2]:
from keras.layers import Dense,Activation
from keras.models import Sequential
from keras.utils import np_utils

Using TensorFlow backend.


In [3]:
df = pd.read_csv('/Users/rajatsaini/Desktop/Titanic_survivors/titanic.csv')
test_file = pd.read_csv('/Users/rajatsaini/Desktop/Titanic_survivors/test.csv')

In [4]:
print df.shape
print df.columns

(891, 12)
Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')


In [5]:
df = df.drop(['Name'],axis=1)
test_file = test_file.drop(['Name'],axis=1)

In [6]:
print df.columns
print test_file.columns

Index([u'PassengerId', u'Survived', u'Pclass', u'Sex', u'Age', u'SibSp',
       u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')
Index([u'PassengerId', u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch',
       u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')


In [7]:
print df['Sex'].isnull().values.any()
# np_utils.to_categorical?

False


In [8]:
# df = df.values
# test_file = test_file.values

In [9]:
# Sex = df['Sex']

In [10]:
# print type(df['Sex'])
# print len(Sex)
# print type(Sex)
# Sex = np.array(Sex)

In [11]:
# print type(Sex)

In [12]:
# df['Sex'] = np_utils.to_categorical(Sex)

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
df = df.apply(le.fit_transform)

In [16]:
ids = test_file['PassengerId']

In [17]:
# print ids

In [18]:
# print df

In [19]:
le2 = LabelEncoder()
test_file = test_file.apply(le2.fit_transform)

In [20]:
# print test_file

In [21]:
df = df.drop(['PassengerId'],axis=1)
test_file = test_file.drop(['PassengerId'],axis=1)

In [22]:
print df.columns
print test_file.columns

Index([u'Survived', u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Ticket',
       u'Fare', u'Cabin', u'Embarked'],
      dtype='object')
Index([u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Ticket', u'Fare',
       u'Cabin', u'Embarked'],
      dtype='object')


In [23]:
df['Sex'] = np_utils.to_categorical(df['Sex'])
test_file['Sex'] = np_utils.to_categorical(test_file['Sex'])

In [31]:
print df[:5]
# print test_file['Sex']

[[   0.    2.    0.   28.    1.    0.  523.   18.    0.    4.]
 [   1.    0.    1.   51.    1.    0.  596.  207.  768.    2.]
 [   1.    2.    1.   34.    0.    0.  669.   41.  509.    4.]
 [   1.    0.    1.   47.    1.    0.   49.  189.  742.    4.]
 [   0.    2.    0.   47.    0.    0.  472.   43.  510.    4.]]


In [28]:
df = df.values
test_file = test_file.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [29]:
print type(df)
print type(test_file)

<type 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


In [27]:
split = int(0.75*df.shape[0])
print split

train_x = df[:split][1:]
train_y = df[:split][0]
test_x = df[split:][1:]
test_y = df[split:][0]
print train_x.shape,train_y.shape
print test_x.shape,test_y.shape

668
(667, 10) (10,)
(222, 10) (10,)


In [36]:
model = Sequential()
model.add(Dense(5, input_shape=(10,)))
model.add(Activation('relu'))

model.add(Dense(2))
model.add(Activation('softmax'))

model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_3 (Dense)                  (None, 5)             55          dense_input_2[0][0]              
____________________________________________________________________________________________________
activation_3 (Activation)        (None, 5)             0           dense_3[0][0]                    
____________________________________________________________________________________________________
dense_4 (Dense)                  (None, 2)             12          activation_3[0][0]               
____________________________________________________________________________________________________
activation_4 (Activation)        (None, 2)             0           dense_4[0][0]                    
Total params: 67
Trainable params: 67
Non-trainable params: 0
_____________________________

In [37]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [39]:
model.fit(train_x,train_y,batch_size=8,nb_epoch=15,verbose=2,validation_data=(test_x,test_y))

ValueError: Error when checking model target: expected activation_4 to have shape (None, 2) but got array with shape (10, 1)